language: node_js

node_js:
  - "node"

script:
  - npm run build
#  - npm test

before_deploy:
  - bash bin/before_deploy.sh

deploy:
  provider: pages
  target-branch: build
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

branches:
  except:
    - build
